apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
